feat: change docker file

diff --git a/.github/workflows/deploy_aws.yaml b/.github/workflows/deploy_aws.yaml
--- a/.github/workflows/deploy_aws.yaml
+++ b/.github/workflows/deploy_aws.yaml
@@ -20,16 +20,22 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1
 
-      - name: Install dependencies
-        run: |
-          python -m venv venv
-          source venv/bin/activate || echo "Virtual environment activation failed"
-          pip install -r requirements.txt
+      # - name: Install dependencies
+      #   run: |
+      #     python -m venv venv
+      #     source venv/bin/activate || echo "Virtual environment activation failed"
+      #     pip install -r requirements.txt
 
-      - name: Deploy application to EC2
-        run: |
-          echo "ENV_VARIABLE=${{ secrets.ENV_VARIABLE }}" >> .env
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
-          chmod 400 ssh_key.pem
-          ssh -o "StrictHostKeyChecking=no" -i ssh_key.pem ec2-user@ec2-3-84-95-162.compute-1.amazonaws.com "cd ./python-cart && git pull origin main && source venv/bin/activate && pip install -r requirements.txt"
+      # - name: Deploy application to EC2
+      #   run: |
+      #     echo "ENV_VARIABLE=${{ secrets.ENV_VARIABLE }}" >> .env
+      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
+      #     chmod 400 ssh_key.pem
+      #     ssh -o "StrictHostKeyChecking=no" -i ssh_key.pem ec2-user@ec2-3-84-95-162.compute-1.amazonaws.com "cd ./python-cart && git pull origin main && source venv/bin/activate && pip install -r requirements.txt"
 
+
+      - name: Build Docker image
+        run: docker build -t python-billing .   
+
+      - name: Run Docker container
+        run:  docker run python-billing  
